---

- hosts: all
  become: true
  tasks:

#----------------[Ubuntu]--------------------

  - name: install apache2 package and php support
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes # this replaces the entire "update repository index" task
    when: ansible_distribution == "Ubuntu"

#----------------[CentOS]--------------------

  - name: install apache2 package and php support
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
